packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/react": "~19.0.10"
  "@types/react-dom": "^19.1.6"
  "@types/node": "^20.10.6"
  "babel-plugin-react-native-web": "0.20.0"
  "eslint": "^9.25.0"
  "eslint-config-expo": "~9.2.0"
  "eslint-config-next": "15.3.4"
  "react": "19.0.0"
  "react-dom": "19.0.0"
  "react-native": "0.79.4"
  "react-native-web": "~0.20.0"
  "typescript": "~5.8.3"